platform :ios, '12.0'

target 'YourProjectName' do
  config = use_native_modules!

  use_frameworks! :linkage => :static

  target 'YourProjectNameTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper for iOS debugging
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
